### ISSUE TITLE
Can EPIC accept CPM or microarray data?

### ISSUE THREAD

**Issue by thelingxichen** [GfellerLab/EPIC#11]
Hi there,

It looks like EPIC is designed for RNA-Seq TPM data. Is RNA-Seq CPM data ok?
How about fitting microarray data into EPIC? If possible, is any normalization (like quatile) required?

Many thanks,
Lindsay

**Comment by jracle85** [comment]
Dear Lindsay,

Thank you for your questions.

**First for CPM data:**
Please check my answer to a similar question given here: [https://github.com/GfellerLab/EPIC/issues/9](https://github.com/GfellerLab/EPIC/issues/9)

**Then, concerning microarray data:**
I do not recommend using EPIC on microarray. Similarly to the case of CPM data, the scales between the genes won't be the same for microarrays and RNA-seq. Also, the amount of the otherCells will likely not be estimated well due to the difficulty to know really what is the value 0 in microarray, and because the linearity relationship between the amount of mRNA and measured microarray value is not always holding.
But if needed, you could try using EPIC on microarray data as well (I’d recommend using a linear scale, not log, where the value 0 for a gene should correspond to the absence of expression of this gene), and ideally, if possible, it would be better to redefine your own reference gene expression profiles based on microarray data.

Best regards,

Julien
