### ISSUE TITLE
This version is not compatible with R >=4.0.0

### ISSUE THREAD

**Issue by yhren1994** [GfellerLab/EPIC#12]
Hi there,
It seems that this version of EPIC could only work on R<=3.6.3. Therefore, I hope there will be a new version which could work on R >=4.0.0.
Many thanks!
yhren

**Comment by jracle85** [comment]
Hello,

I'm using EPIC with R 4.0.2 and it works.

What is the issue that you're Having? It seems that sometimes an issue comes during the installation with
`devtools::install_github("GfellerLab/EPIC", build_vignettes=TRUE)`

In such a case if you set `build_vignettes=FALSE` instead of `TRUE` could help (and this issue possibly also disappears if the different installed packages are updated prior to installation, allowing to keep the `build_vignettes=TRUE`).

I hope this works for you!

Best wishes,

Julien

**Comment by yhren1994** [comment]
> Hello,
> 
> I'm using EPIC with R 4.0.2 and it works.
> 
> What is the issue that you're Having? It seems that sometimes an issue comes during the installation with `devtools::install_github("GfellerLab/EPIC", build_vignettes=TRUE)`
> 
> In such a case if you set `build_vignettes=FALSE` instead of `TRUE` could help (and this issue possibly also disappears if the different installed packages are updated prior to installation, allowing to keep the `build_vignettes=TRUE`).
> 
> I hope this works for you!
> 
> Best wishes,
> 
> Julien

It works! Thanks a lot!
