### ISSUE TITLE
mRNA_cell warning

### ISSUE THREAD

**Issue by ahy1221** [GfellerLab/EPIC#2]
Thanks for providing such great software !
As the paper said that "The renormalization by mRNA content  appeared to be important for predicting actual cell fractions" and the code , the mRNA_cell argument looks quite important for cell fraction estimation. If I understand right, these mRNA_cell values should be acquired by some wet-lab experiment (FA analysis for example). 
In this setting, what if I cann't get such values for my customized reference profile ? Even for the TRef, I still got warnings about "mRNA_cell value unknown for some cell types and for these but this might bias the true cell proportions from all cell types."". I am wondering taht is there any way to handle such situation ?

**Comment by jracle85** [comment]
Hello,
Thank you for your comment!

Indeed, we showed that the mRNA per cell value is helping to determine more accurately the absolute proportions of the various cell types. And yes, these mRNA_cell values were obtained from some wet-lab experiments.

If you don't have such data, please note that EPIC will still be able to predict the proportions of mRNA coming from the various cell types, which can be used as a direct proxy to the proportion of the various cell types (this is what all other cell deconvolution tools do; there EPIC will still bring some other improvements vs these other tools like the presence of the "other cells").
In such a case, I would nevertheless more consider the relative proportions between the samples for a same cell type than considering these proportions as true absolute proportions of a given cell type. In most of the cases, this would hold well. It could break in some cases; for example if you imagine two bulk samples where the mRNA proportions of T cells are 20% in both but in one there are 80% of neutrophils and in the other bulk it is 80% of NK cells. From the mRNA proportions you would assume that both samples have the same amount of T cells, but in fact the sample with neutrophils would have a smaller absolute proportion of T cells (because neutrophils have less mRNA/cell).

If you only have partial knowledge of these mRNA abundances (like for TRef where we know it except for the macrophages and CAFs), you could still include the value known and use some average value for the other cell types without knowledge of mRNA abundance. This would still help in improving the general cell proportions. Additionally, if you then see that the mRNA proportions of these "missing" cell types are low (as returned EPIC), then even if you don't correct the results with the true mRNA/cell abundances of these cells, it wouldn't really have a big impact on the results. On the other side, if there are many of these cells (with unknown mRNA abundance) in your bulk sample, the results might be a little bit biased, but the effect should be quite similar for all samples and thus not have a too big importance (maybe you wouldn’t be fully able to tell if there are more CAFs than Tcells for example, but you should still have a good estimate of which sample has more CAFs (or Tcells) than which other sample for example).


Finally if you really would like to get these mRNA abundances but aren't able to make a direct experiment of it, here are some other indirect ways that could maybe be used to have some estimate of these:
- Instead of directly measuring these cell types experimentally, if you have some dataset where the cell proportions of your cells are known and you have the corresponding bulk datasets, you could do some parameter fitting to determine which mRNA abundances are needed to best reflect the true cell proportions.
- If you have RNA-seq data from your cell types isolated, and you have some spike-ins of known concentration in this RNA-seq data, you could estimate the mRNA abundances with help of these spike-ins (maybe it would even be possible to use the expression of house-keeping genes or else for which it is known the concentration remains about constant in all cell types).

Best regards,

Julien
