### ISSUE TITLE
PMBC extracted data (not working)

### ISSUE THREAD

**Issue by bsla98** [GfellerLab/EPIC#5]
Hello!

I am trying to run EPIC on some synthetic mixtures extracted from PBMC data and another stromal cell type. We have 100 random selected synthetic mixes for each of the three files we want to run. I have tried both the online tool and the installed tool on cluster; for the online tool, as soon as I upload the bulk mix, the tool says "Disconnected from server" and prompts to reload the page. On the cluster, I am getting the error "Attempt to set colnames on an object with less than two dimensions".

The tool works on some other sets we have tried. Gene names and any file formatting errors have been checked for the PBMC sets as well, but with no avail. 

Any help would be greatly appreciated! Thank you.

Best,
Benjamin Shou

**Comment by jracle85** [comment]
Hello Benjamin,
Thank you for your question.

From the error messages you write, it seems that there is some issue with the format of your input data.

Maybe in the R-package your data is in the form of a vector instead of a matrix? This could be an error with the bulk input data or with the reference gene expression profiles if you use your own ones.

In the web tool, the disconnection from server happens in general if there is an issue with the files that you upload. This could happen for example if some gene names are duplicated, or if your input file isn't a tab-delimited file. Please note however that I've now updated the web tool: instead of getting disconnected if a bad input file is uploaded, you should instead receive some error message (except if the error is coming from elsewhere).

If your files are of the correct format and you still receive this error, please send me ([julien.racle@unil.ch](mailto:julien.racle@unil.ch)) some example data that is crashing so that I could look in more details into this issue.

Best wishes,
Julien
