### ISSUE TITLE
Adding TRef and BRef references

### ISSUE THREAD

**Issue by kgaonkar6** [GfellerLab/EPIC#6]
Hello,

Thank you for developing this useful tool to identify cell fractions in tumor cells. I have already used the tool using reference datasets and I do get some useful results.
However, an investigator I work with is interested in looking at all immune cells and tumor infiltrating cell fractions in our bulk dataset. Is this possible to combine TRef and BRef from existing reference dataset that come with the package if yes, how should I go about doing this?

If I have to create a custom reference , how would you suggest I go about generating that?

Thank you,
Krutika

**Comment by jracle85** [comment]
Hello,

Thank you for the question.

As the two reference profiles are coming from two different types of data (bulk RNA-seq vs single-cell RNA-seq), and the RNA-seq weren't mapped to the same reference genome (they don't have the same list of genes), it may not be ideal to just combine together these two reference profiles.

If you really need it, you should probably better start back from the original data (the datasets used are publicly available and referenced in our publication as well as in the R package help documents (e.g. ?EPIC::TRef ; ?EPIC::BRef )), check how to correct for batch effects so that the cell types that are present in both datasets cluster together independently of the sample/study of origin, and then re-build reference profiles based on this whole data. (when doing this, for the sc-RNA-seq samples, instead of considering each single cell independently, it may be better to create in silico bulk samples where you'd for example average the gene expression per patient and cell type).

You could also integrate additional more recent studies (maybe sc-RNA-seq) that included the cell types that you're interested in.

For the details on how the reference profiles were then built, you can look at the methods section of our publication explaining how these were built as well as how the marker genes were selected (and you could also look at the help in our R package for how these should be implemented to use with the package).

Best wishes,

Julien
